name: 'career-compass'
services:
  user-db:
    image: postgres:16-alpine
    container_name: user-db
    environment:
      - POSTGRES_USER=tasriad
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userDB
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m