name: User Service
'on':
  push:
    paths:
      - user_service/**
    branches:
      - '**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./user_service
      DB_URL: 'jdbc:postgresql://localhost:15432/userDB'
      DB_USERNAME: tasriad
      DB_PASSWORD: password
      DOCKER_IMAGE_NAME: '${{ secrets.DOCKERHUB_USERNAME }}/career-compass-user_service'
    defaults:
      run:
        working-directory: '${{ env.working-directory }}'
    services:
      postgres:
        image: 'postgres:16-alpine'
        ports:
          - '15432:5432'
        env:
          POSTGRES_USER: tasriad
          POSTGRES_PASSWORD: password
          POSTGRES_DB: userDB
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s
          --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Wait for PostgreSQL to be ready
        run: |
          while ! pg_isready -h localhost -p 15432 -U ${{ env.DB_USERNAME }}; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21.0.3
          distribution: temurin
          cache: maven
      - name: Grant execute permission for Maven wrapper
        run: chmod +x ./mvnw
      - name: Build with Maven
        run: ./mvnw -ntp verify

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_ACCESS_TOKEN }}'

      - name: Build Docker image
        run: './mvnw -e spring-boot:build-image -DskipTests'

      - name: Push Docker image
        run: 'docker push ${{ env.DOCKER_IMAGE_NAME }}'
